import shelve

db = shelve.open('bins.db', writeback=True)

db['bins'] = {
    '1': {'region': 'North', 'type': 'E-recycling Bin', 'name': 'Marsiling Industrial Estate Road 8', 'address': '30 Marsiling Industrial Estate Road 8, Singapore 739193'},
    '2': {'region': 'North', 'type': 'Recycling Bin', 'name': 'Giant Supermarket - Woodlands Mart','address': '768 Woodlands Avenue 6, #01-34 Woodlands Mart, Singapore 730768'},
    '3': {'region': 'North', 'type': 'Recycling Bin', 'name': '876 Woodlands Street 83','address': '876 Woodlands Avenue 9, #01-256, Singapore 730876'},
    '4': {'region': 'North', 'type': 'E-recycling Bin', 'name': '336A Sembawang Crescent', 'address': '336A Sembawang Crescent, Singapore 751336'},
    '5': {'region': 'North', 'type': 'Recycling Bin', 'name': 'Giant Supermarket - Woodlands North Plaza', 'address': 'Blk 883 Woodlands Street 82, #01-498, Singapore 730883'},
    '6': {'region': 'North', 'type': 'E-recycling Bin', 'name': '20 Woodlands Link', 'address': '20 Woodlands Link, Singapore 738733'},
    '7': {'region': 'North', 'type': 'Recycling Bin', 'name': 'Block 406A HDB Sembawang (MSCP)', 'address': '406A Sembawang Drive, Singapore 751406'},
    '8': {'region': 'North', 'type': 'E-recycling Bin', 'name': 'Northpoint City Centre', 'address': 'Blk 930 Yishun Avenue 2, Northpoint City Centre, Singapore 769098'},
    '9': {'region': 'North', 'type': 'E-recycling Bin', 'name': 'Tzu Chi Humanistic Youth Centre', 'address': '30A Yishun Central 1, Singapore 768796'},
    '10': {'region': 'North', 'type': 'Recycling Bin', 'name': 'Challenger (Sun Plaza)', 'address': '30 Sembawang Drive, #02-06 Sun Plaza, Singapore 757713'},
    '11': {'region': 'North', 'type': 'Recycling Bin', 'name': 'Woodgrove Community Centre', 'address': '353 Woodlands Avenue 1, #01-753, Singapore 730353'},
    '12': {'region': 'North', 'type': 'Recycling Bin', 'name': 'Fuchun Community Club', 'address': '1 Woodlands Street 31, Singapore 738581'},
    '13': {'region': 'North', 'type': 'Recycling Bin', 'name': 'Sheng Siong Supermarket - Marsiling Admiralty Park', 'address': '202 Marsiling Drive, #01-138, Singapore 730202'},
    '14': {'region': 'North', 'type': 'Recycling Bin', 'name': 'Popular Bookstore - Northpoint City', 'address': '930 Yishun Avenue 2, #03-12, Singapore 769098'},
    '15': {'region': 'North', 'type': 'Recycling Bin', 'name': 'Nee Soon East Community Club','address': '1 Yishun Ave 9, Singapore 768893'},
    '16': {'region': 'North', 'type': 'Recycling Bin', 'name': 'Block 602 Yishun Street 61','address': 'Blk 602 Yishun Street 61, Singapore 760602'},

    '17': {'region': 'Northeast', 'type': 'E-recycling Bin', 'name': 'JTC Aviation Two','address': '690 West Camp Road, Singapore 797523'},
    '18': {'region': 'Northeast', 'type': 'E-recycling Bin', 'name': 'Sengkang General Hospital','address': '110 Sengkang East Way, Singapore 544886'},
    '19': {'region': 'Northeast', 'type': 'Recycling Bin', 'name': 'Punggol West Community Centre','address': 'Blk 259C Punggol Fld, Singapore 823259'},
    '20': {'region': 'Northeast', 'type': 'Recycling Bin', 'name': '1 Sengkang Square','address': '1 Sengkang Square, #B1-52/53, Compass One, Singapore 545078'},
    '21': {'region': 'Northeast', 'type': 'Recycling Bin', 'name': 'Yio Chu Kang Community Club','address': 'Blk 633 Ang Mo Kio Avenue 6, #01-5135 8, Singapore 560633'},
    '22': {'region': 'Northeast', 'type': 'E-recycling Bin', 'name': 'Ang Mo Kio Hub Singtel Store','address': '53 Ang Mo Kio Avenue 3, #B1-54/55/56/57 AMK Hub, Singapore 569933'},
    '23': {'region': 'Northeast', 'type': 'Recycling Bin', 'name': 'Canopy Coffee Club','address': 'Blk 260 Ang Mo Kio Street 21, Singapore 560260'},
    '24': {'region': 'Northeast', 'type': 'E-recycling Bin', 'name': 'Highland Centre Condominium','address': '22 Yio Chu Kang Road, Singapore 545535'},
    '25': {'region': 'Northeast', 'type': 'Recycling Bin', 'name': 'Shell - Serangoon Garden','address': '49 Serangoon Garden Way, Singapore 555944'},
    '26': {'region': 'Northeast', 'type': 'Recycling Bin', 'name': 'Giant Supermarket - Buangkok Crescent','address': 'Blk 982 Buangkok Cres, #01-01, Singapore 530982'},
    '27': {'region': 'Northeast', 'type': 'E-recycling Bin', 'name': 'Block 326D Anchorvale Road','address': 'Blk 326D Anchorvale Rd, Singapore 544326'},
    '28': {'region': 'Northeast', 'type': 'Recycling Bin', 'name': 'Sheng Siong Supermarket - Waterway Sundew','address': 'Blk 660A , #01-01 Waterway Sundew, Singapore 821660'},
    '29': {'region': 'Northeast', 'type': 'Recycling Bin', 'name': 'Sengkang General Hospital','address': '110 Sengkang E Wy, Singapore 544886'},
    '30': {'region': 'Northeast', 'type': 'E-recycling Bin', 'name': 'Block 274C Compassvale Bow','address': 'Blk 274C Compassvale Bow, Singapore 543274'},

    '31': {'region': 'East', 'type': 'Recycling Bin', 'name': 'Block 148 Pasir Ris','address': 'Blk 148 Pasir Ris Street 13, Singapore 510148'},
    '32': {'region': 'East', 'type': 'Recycling Bin', 'name': 'Tampines Ville RN','address': 'Blk 848 Tampines St 82, Singapore 520848'},
    '33': {'region': 'East', 'type': 'Recycling Bin', 'name': 'FairPrice Chai Chee Avenue','address': 'Blk 29B Chai Chee Ave, #01-62 Ansar Garden, Singapore 462029'},
    '34': {'region': 'East', 'type': 'E-recycling Bin', 'name': 'Block 738 Pasir Ris Drive 10','address': 'Blk 738 Pasir Ris Drive 10, Singapore 510738'},
    '35': {'region': 'East', 'type': 'Recycling Bin', 'name': 'Shell - Siglap','address': '40 Upper East Coast Rd, Singapore 455212'},
    '36': {'region': 'East', 'type': 'Recycling Bin', 'name': 'Bedok Industrial Park E','address': '3013 Bedok Industrial Park E, Pavilion, Bedok Industrial Park E 489978'},
    '37': {'region': 'East', 'type': 'Recycling Bin', 'name': 'Tampines Changkat Zone 8 Residents Network','address': 'Blk 364 Tampines Street 34, #01-133, Singapore 520364'},
    '38': {'region': 'East', 'type': 'E-recycling Bin', 'name': 'Shell - Tampines','address': '9 Tampines Avenue 2, Singapore 529731'},
    '39': {'region': 'East', 'type': 'E-recycling Bin', 'name': 'Block 24 Bedok','address': 'Blk 24 Chai Chee Rd, Singapore 460024'},
    '40': {'region': 'East', 'type': 'Recycling Bin', 'name': 'Block 135 Pasir Ris','address': '135 Pasir Ris Street 11, Singapore 510135'},

    '41': {'region': 'West', 'type': 'Recycling Bin', 'name': 'Yuhua Community Club','address': '90 Boon Lay Wy, Singapore 609958'},
    '42': {'region': 'West', 'type': 'Recycling Bin', 'name': 'FairPrice Supermarket - Taman Jurong Shopping Centre','address': 'Blk 399 Yung Sheng Rd, #01-35, Singapore 610399'},
    '43': {'region': 'West', 'type': 'E-recycling Bin', 'name': 'Block 318 Clementi','address': 'Blk 318 Clementi Ave 4, Singapore 120318'},
    '44': {'region': 'West', 'type': 'E-recycling Bin', 'name': 'National Library Board','address': '21 Jurong East Central 1, Singapore 609732'},
    '45': {'region': 'West', 'type': 'Recycling Bin', 'name': 'NTUC FairPrice - Bukit Batok MRT Station','address': '10 Bukit Batok Central, #01-08 MRT Station, Singapore 659958'},
    '46': {'region': 'West', 'type': 'E-recycling Bin', 'name': 'Pioneer Zone 9 RN','address': '602 Jurong West St 65, #01-175, Singapore 640602'},
    '47': {'region': 'West', 'type': 'Recycling Bin', 'name': 'Ng Teng Fong General Hospital Tower B','address': '1 Jurong East Street 21, Singapore 609606'},
    '48': {'region': 'West', 'type': 'Recycling Bin', 'name': 'Giant Hypermarket - Pioneer Mall','address': 'Blk 638 Jurong West Street 61, #03-01, Singapore 640638'},
    '49': {'region': 'West', 'type': 'E-recycling Bin', 'name': 'Nanyang Meadows - Block 98','address': 'Blk 98 Nanyang Cres, Nanyang Meadows Staff Housing, Singapore 637665'},
    '50': {'region': 'West', 'type': 'Recycling Bin', 'name': '2 Jurong East Central 1','address': '2 Jurong East Central 1, Rear Entrance, Capitaland JCube 609731'},
    '51': {'region': 'West', 'type': 'E-recycling Bin', 'name': 'Block 297D Choa Chu Kang','address': 'Blk 297D Choa Chu Kang Ave 2, Singapore 684297'},
    '52': {'region': 'West', 'type': 'Recycling Bin', 'name': 'Sheng Siong Supermarket - Clementi Ave 2','address': 'Blk 352 Clementi Ave 2, #01-91/93/95 Shopping Centre, Singapore 120352'},

    '53': {'region': 'Central', 'type': 'E-recycling Bin', 'name': 'Marymount Community Club','address': '191 Sin Ming Ave, Main Lobby, Singapore 575738'},
    '54': {'region': 'Central', 'type': 'E-recycling Bin', 'name': 'Toa Payoh West Community Club','address': '200 Lor 2 Toa Payoh, Side of Building, Singapore 319642'},
    '55': {'region': 'Central', 'type': 'Recycling Bin', 'name': 'Environment Building','address': '40 Scotts Rd, Singapore 228231'},
    '56': {'region': 'Central', 'type': 'E-recycling Bin', 'name': "King's Centre",'address': '390 Havelock Rd, Singapore 169662'},
    '57': {'region': 'Central', 'type': 'Recycling Bin', 'name': 'Kitchener Complex','address': 'Blk 809 French Rd, Kitchener Complex, Main Lobby, Singapore 200809'},
    '58': {'region': 'Central', 'type': 'Recycling Bin', 'name': 'FairPrice Finest Funan Mall','address': '107 N Bridge Rd, #B1-10 Funan, Singapore 179105'},
    '59': {'region': 'Central', 'type': 'Recycling Bin', 'name': 'Guoco Tower B2 Atrium','address': '7 Wallich St, Guoco Tower, B2 Atrium Beside Escalator, Singapore 078884'},
    '60': {'region': 'Central', 'type': 'E-recycling Bin', 'name': 'Revenue Centre','address': '55 Newton Rd, Level 2, Singapura 307987'},
    '61': {'region': 'Central', 'type': 'E-recycling Bin', 'name': 'Singtel Shop 313@somerset','address': '313 Orchard Rd, #03-31/32/33/34/35/36 313 Somerset, Singapore 238895'},
}

db.close()
print("Sample bin data has been added to bins.db!")
